craft_image_processing:
  norm_mean: (0.485, 0.456, 0.406)
  norm_variance: (0.229, 0.224, 0.225)
  canvas_size: 1280
  mag_ratio: 1.5

text_detection:
  text_threshold: 0.5
  low_text: 0.3
  link_threshold: 0.6
  poly: False
  refine: False

text_recognition:
  resize_canvas: (56, 224) # (height, width)
  sorting_threshold: 0.5
  char_list:
    [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z",
    ]
