artifacts_root: artifacts

demo_image:
  image_url: https://editor.analyticsvidhya.com/uploads/41548id_craft_av.jpg
  image_dir: artifacts/image/input

image_processing:
  image_path: artifacts/image/input/demo.jpg
  result_path: artifacts/image/result

text_detection:
  craft_weights: artifacts/models/craft/craft_mlt_25k.pth
  refiner_weights: artifacts/models/craft/craft_refiner_CTW1500.pth
  loaded_image_path: artifacts/image/result/demo_transformed.jpg
  normalized_image_path: artifacts/image/result/demo_normalized.jpg
  resized_data_path: artifacts/image/result/resized_data.pkl

text_recognition:
  #crnn_weights: artifacts/models/crnn/crnn_epoch_2_12.h5
  crnn_weights_digital: artifacts/models/crnn/crnn_synthdata_keras_9_11char_epoch_04.h5
  crnn_weights_handwritten: artifacts/models/crnn/crnn_synthdata_keras_9_11char_epoch_04.h5
  crnn_input_path: artifacts/image/result
  crnn_output_path: artifacts/output/crnn

text_post_processing:
  text_input_path: artifacts/output/crnn
